apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://gitlab.com/tzero-git/tz/infrastructure/argocd-panicker
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true